import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import "./AboutUs.css";

const img = {
  hero:"https://lh3.googleusercontent.com/aida-public/AB6AXuCvsjHKYhGsQKQLnTkuLKUhucGPa4EhIXvtQecRdi3WGOQ6A4Bckagl3JYzXm7U3YK3wI4lCSVctzHoFjepG5GsY7y0-HOZ3mS0LwcKSXk1lXGg14FiVpBnSRdWGEMbK-ci0W8kaf3eR9uc5Hg-PmdzH7uSyT4Xis5ZqzhL1Y_MYB6BV9xNJp05qdtm3GGtHzLgBWZTWciZ7pPdNUG3oRwxCoZ9qc4P9lavMtFd1EDEACkWWfvBNxKRpY6_gTbMHx9QnOa8jhr2nDs",
  loom:"https://lh3.googleusercontent.com/aida-public/AB6AXuCtJ_jzpYNS7Qu1kW3V4dodYzIBg1yrR91lpbVwqX17xz_doxxG6TAZoFr7Amw8osmSDPythp0bhI_ru2cnCcQD8cP9FMBlEKqL-P0m5lPQYL0X6ODcDTNybsQfggf7ejhRTV680HaBM-1-t0hgyM3GltazYWHQJE8Ork9Q7rwAE-1fifcUfVp1yns72knWPqkZ5deGP8KjZlyqGvA14D9vaiqz3BVUW2u_lRpBtKJhMiZZGCmCBbi6QfyRXEezhng0qnDegwgxON4",
  old:"https://lh3.googleusercontent.com/aida-public/AB6AXuAyCP4ueScOqupcrIVA7D8G_8NTKoChjNYbfxLog7G7CAemPB0cSc8SQK-3i8L8il8iyZ7wx3ycGDjA_o5sgY-T8ya0HBDn8A6_Shqa6wkgOSO0isRL2zq62AesyBzgZchpI8Ry8kHzgzbePmv2TAzKYPOI58o4VIuebj50pbUr2xZzUjjcvGOU8cb6ESj_0zj0M8Un4Frylien60U2U0GZ3Ehspy4lbLCeFgxftJ6GlV94Wjw9Q9scUak1DBAr9U6R6V7mTvnJteQ",
  shop:"https://lh3.googleusercontent.com/aida-public/AB6AXuCOVVayrGCvC33nCSFH97B9s1IXQjajwiDkVzg67xgnlMUrIQgvYHp2WTcxFmIbPuPAp8ztQUaXkpfHFvyirYmbzqmksZIQrYdRWpUQIQTZ_950pvpwcPf0aSzDsYpKqCmM8wr8-CJOtCyHliFEMhNOcQyN4J4AB2gRl6uSWsv7go2bbSsHilUjUg0tImdgmVTXbdiQToDbDvfU0yTl3byb9lyz-5EJteNXQ7tqiGFtHc_CNqB3LJ18AaA5CE4_nTDOGsQDfuXxv7o",
  lab:"https://lh3.googleusercontent.com/aida-public/AB6AXuDPwiD9bstyXsceKJ9zsSCRxMPsBw0EJzVAM6tWpg-qYS7Hpq8-qXF1HsUMVO4SUi8fc1_5aBwaUiGSN6nqex5ksXQNDVPwgFc_sPFnyeMpERnBxPkWCDpceXlBgmR41sEDD5sYr1AjvIVFTCLAhcS7Kobc7ZcnB5n1peY7P6V12Mjnx-jsPft21hFUigerwaaYE-FKuLrj7gnzbQZb7VAYOjZ-kRG0M7QTEDbz8NoXnqteEr_Lfq7FFdHTWRDTCbRAFbCD8vDuXfQ",
  velvet:"https://lh3.googleusercontent.com/aida-public/AB6AXuBzkkL-lll8qThyUTPIDsyEoYav2pVb0-v_d2oG5PcRk08nZ9h1yiPKAxujMWtiVDvqcOupidNoV4rFhHMopqvdFj52hi86qcL0Eiox7Miut5BS-MOQ0_6bhEPdJ5lyRPKFRse1gXNahR9wRjdj7deeDQZGZ8XqppQsZgrxBSrtdTA9QpBgGi8rTOutH7RmzT62DQ3BCywDV9OZATn5YXp-KUHOBg73Ze-hLXjrqKNqgJkqbU9hnwerJ5t4kpvmh6WSKKYIKYxSLac",
  swatches:"https://lh3.googleusercontent.com/aida-public/AB6AXuCPLQvPYnSS5zC_lk6xP0jOoHZRlrdDxdSW7f32gVyGqeIxhgISmVonG1CeUB1sbmYpSfha_B8nbFBabqEV-Ld8jWq__WdYeQD-qlM_dWUGiemc8xre-mcvPblvxVk9CECK26hnCDsYbBiK-d08mtuRyTcu10zNF8fb977aSUpfJy3ZGbrayYlsEty25PNZsalV5RIpJ-cSFCvV97-uvkAgTjUz0DEP1g9Stnsr7cR17p8u3OXOR9utksAoY_AAn6N_htum2zFnKf0"
};
const links=[["HOME","/"],["CATALOGS","/catalogs"],["FABRIC MOCKUP","/mockup"],["ABOUT US","/about-us"],["SERVICES","/services"],["DASHBOARD","/dashboard"]];

function Header(){const [open,setOpen]=useState(false);const {pathname}=useLocation();return <header className="au-header"><div className="au-nav"><Link className="au-brand" to="/">ANC NAJJAR</Link><nav className="au-links">{links.map(([n,to])=><Link className={pathname===to?"active":""} to={to} key={to}>{n}</Link>)}</nav><div className="au-actions"><button>EN/AR</button><Link to="/request-sample">REQUEST SAMPLE</Link></div><button className="au-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?"×":"☰"}</button></div>{open&&<nav className="au-mobile">{links.map(([n,to])=><Link onClick={()=>setOpen(false)} to={to} key={to}>{n}</Link>)}</nav>}</header>}
const timeline=[
  ["1982","ANC Najjar was founded with a single loom and a commitment to quality.",img.old],
  ["2005","Expansion into global markets, establishing offices in London and Dubai.",img.shop],
  ["Today","Leading the industry with smart fabrics and sustainable manufacturing processes.",img.lab]
];

export default function AboutUs(){return <div className="au-page"><Header/><main>
  <section className="au-hero" style={{backgroundImage:`linear-gradient(#1a1c1c4d,#1a1c1c4d),url(${img.hero})`}}><div><span>ESTABLISHED 1982</span><h1>Legacy in Every Thread</h1><p>Four decades of textile excellence, supplying the world's most prestigious<br/> interiors with fabrics that define luxury and durability.</p></div></section>
  <section className="au-section au-story"><div><h2>The Art of the Loom</h2><i/><p>Our journey began in a small atelier, driven by a singular passion for textures that tell a story. ANC Najjar has evolved into a global powerhouse, yet our soul remains anchored in the tactile precision of the master weaver.</p><blockquote>“Luxury isn't just about the material; it's about the heritage woven into its very fiber.” — Founder's Vision</blockquote><button>DISCOVER OUR PROCESS</button></div><figure><img src={img.loom} alt="Traditional loom weaving fabric"/></figure></section>
  <section className="au-values-bg"><div className="au-section au-values"><article className="au-vision"><span>◉</span><h3>Our Vision</h3><p>To redefine the global interior landscape by merging ancestral weaving techniques with sustainable innovation, becoming the definitive choice for architects and designers worldwide.</p></article><article className="au-mission"><b>♞</b><div><h3>Our Mission</h3><p>Delivering uncompromising textile quality through ethically sourced materials and cutting-edge design, ensuring every space we touch resonates with elegance.</p></div></article></div></section>
  <section className="au-section au-history"><header><h2>History in Motion</h2><p>Tracking our growth from a local workshop to an international icon.</p></header><div className="au-timeline">{timeline.map(([year,text,src],i)=><article className={i===1?"reverse":""} key={year}><div><h4>{year}</h4><p>{text}</p></div><i/><img className={i===0?"gray":""} src={src} alt={`${year} milestone`}/></article>)}</div></section>
  <section className="au-advantage"><div className="au-section au-adv-grid"><div className="au-adv-copy"><small>THE ANC ADVANTAGE</small><h2>Why Leading<br/>Designers<br/>Choose Us</h2>{[["◎","Quality Control","Every meter of fabric undergoes a rigorous 12-point inspection before it leaves our facility."],["◉","Global Presence","Logistics hubs across 4 continents ensure timely delivery for projects of any scale."],["♧","Sustainable Choice","Over 60% of our current catalog is made from recycled or rapidly renewable fibers."]].map(([icon,title,text])=><div className="au-feature" key={title}><b>{icon}</b><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="au-adv-images"><img src={img.velvet} alt="Emerald velvet"/><img src={img.swatches} alt="Neutral fabric swatches"/></div></div></section>
  <section className="au-cta"><h2>Partner with Excellence</h2><p>Join our network of elite designers and bring your vision to life with ANC Najjar textiles.</p><div><Link to="/contact">CONTACT OUR AGENTS</Link><Link to="/catalogs">REQUEST CATALOG</Link></div></section>
  </main><footer className="au-footer"><div className="au-footer-grid"><div><Link className="au-brand" to="/">ANC NAJJAR</Link><p>Excellence in textiles since 1982. Weaving the future of luxury interiors with heritage and innovation.</p></div><div><b>EXPLORE</b><Link to="/catalogs">Catalogs</Link><Link to="/services">Services</Link><a href="#">Sustainability</a></div><div><b>COMPANY</b><Link className="gold" to="/about-us">About Us</Link><Link to="/contact">Contact</Link><a href="#newsletter">Newsletter</a></div><div id="newsletter"><b>NEWSLETTER</b><label><input placeholder="Email Address" type="email"/><button>→</button></label></div></div><div className="au-footer-bottom"><span>© 2024 ANC NAJJAR FURNITURE. All rights reserved.</span><span><a href="#">Privacy Policy</a><a href="#">Terms of Service</a></span></div></footer></div>}
