import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import "./AboutUs.css";

export const img = {
  hero:"https://lh3.googleusercontent.com/aida-public/AB6AXuCvsjHKYhGsQKQLnTkuLKUhucGPa4EhIXvtQecRdi3WGOQ6A4Bckagl3JYzXm7U3YK3wI4lCSVctzHoFjepG5GsY7y0-HOZ3mS0LwcKSXk1lXGg14FiVpBnSRdWGEMbK-ci0W8kaf3eR9uc5Hg-PmdzH7uSyT4Xis5ZqzhL1Y_MYB6BV9xNJp05qdtm3GGtHzLgBWZTWciZ7pPdNUG3oRwxCoZ9qc4P9lavMtFd1EDEACkWWfvBNxKRpY6_gTbMHx9QnOa8jhr2nDs",
  loom:"https://lh3.googleusercontent.com/aida-public/AB6AXuCtJ_jzpYNS7Qu1kW3V4dodYzIBg1yrR91lpbVwqX17xz_doxxG6TAZoFr7Amw8osmSDPythp0bhI_ru2cnCcQD8cP9FMBlEKqL-P0m5lPQYL0X6ODcDTNybsQfggf7ejhRTV680HaBM-1-t0hgyM3GltazYWHQJE8Ork9Q7rwAE-1fifcUfVp1yns72knWPqkZ5deGP8KjZlyqGvA14D9vaiqz3BVUW2u_lRpBtKJhMiZZGCmCBbi6QfyRXEezhng0qnDegwgxON4",
  old:"https://lh3.googleusercontent.com/aida-public/AB6AXuAyCP4ueScOqupcrIVA7D8G_8NTKoChjNYbfxLog7G7CAemPB0cSc8SQK-3i8L8il8iyZ7wx3ycGDjA_o5sgY-T8ya0HBDn8A6_Shqa6wkgOSO0isRL2zq62AesyBzgZchpI8Ry8kHzgzbePmv2TAzKYPOI58o4VIuebj50pbUr2xZzUjjcvGOU8cb6ESj_0zj0M8Un4Frylien60U2U0GZ3Ehspy4lbLCeFgxftJ6GlV94Wjw9Q9scUak1DBAr9U6R6V7mTvnJteQ",
  shop:"https://lh3.googleusercontent.com/aida-public/AB6AXuCOVVayrGCvC33nCSFH97B9s1IXQjajwiDkVzg67xgnlMUrIQgvYHp2WTcxFmIbPuPAp8ztQUaXkpfHFvyirYmbzqmksZIQrYdRWpUQIQTZ_950pvpwcPf0aSzDsYpKqCmM8wr8-CJOtCyHliFEMhNOcQyN4J4AB2gRl6uSWsv7go2bbSsHilUjUg0tImdgmVTXbdiQToDbDvfU0yTl3byb9lyz-5EJteNXQ7tqiGFtHc_CNqB3LJ18AaA5CE4_nTDOGsQDfuXxv7o",
  lab:"https://lh3.googleusercontent.com/aida-public/AB6AXuDPwiD9bstyXsceKJ9zsSCRxMPsBw0EJzVAM6tWpg-qYS7Hpq8-qXF1HsUMVO4SUi8fc1_5aBwaUiGSN6nqex5ksXQNDVPwgFc_sPFnyeMpERnBxPkWCDpceXlBgmR41sEDD5sYr1AjvIVFTCLAhcS7Kobc7ZcnB5n1peY7P6V12Mjnx-jsPft21hFUigerwaaYE-FKuLrj7gnzbQZb7VAYOjZ-kRG0M7QTEDbz8NoXnqteEr_Lfq7FFdHTWRDTCbRAFbCD8vDuXfQ",
  velvet:"https://lh3.googleusercontent.com/aida-public/AB6AXuBzkkL-lll8qThyUTPIDsyEoYav2pVb0-v_d2oG5PcRk08nZ9h1yiPKAxujMWtiVDvqcOupidNoV4rFhHMopqvdFj52hi86qcL0Eiox7Miut5BS-MOQ0_6bhEPdJ5lyRPKFRse1gXNahR9wRjdj7deeDQZGZ8XqppQsZgrxBSrtdTA9QpBgGi8rTOutH7RmzT62DQ3BCywDV9OZATn5YXp-KUHOBg73Ze-hLXjrqKNqgJkqbU9hnwerJ5t4kpvmh6WSKKYIKYxSLac",
  swatches:"https://lh3.googleusercontent.com/aida-public/AB6AXuCPLQvPYnSS5zC_lk6xP0jOoHZRlrdDxdSW7f32gVyGqeIxhgISmVonG1CeUB1sbmYpSfha_B8nbFBabqEV-Ld8jWq__WdYeQD-qlM_dWUGiemc8xre-mcvPblvxVk9CECK26hnCDsYbBiK-d08mtuRyTcu10zNF8fb977aSUpfJy3ZGbrayYlsEty25PNZsalV5RIpJ-cSFCvV97-uvkAgTjUz0DEP1g9Stnsr7cR17p8u3OXOR9utksAoY_AAn6N_htum2zFnKf0"
};
const links=[["HOME","/"],["CATALOGS","/catalogs"],["FABRIC MOCKUP","/mockup"],["ABOUT US","/about-us"],["SERVICES","/services"],["DASHBOARD","/dashboard"]];

export function LegacyAboutHeader(){const [open,setOpen]=useState(false);const {pathname}=useLocation();return <header className="au-header"><div className="au-nav"><Link className="au-brand" to="/">ANC NAJJAR</Link><nav className="au-links">{links.map(([n,to])=><Link className={pathname===to?"active":""} to={to} key={to}>{n}</Link>)}</nav><div className="au-actions"><button>EN/AR</button><Link to="/request-sample">REQUEST SAMPLE</Link></div><button className="au-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?"×":"☰"}</button></div>{open&&<nav className="au-mobile">{links.map(([n,to])=><Link onClick={()=>setOpen(false)} to={to} key={to}>{n}</Link>)}</nav>}</header>}
const timeline=[
  ["1998","Ahmad Al Najjar established the company in Lebanon with a commitment to quality fabrics and lasting customer relationships.",img.old],
  ["2022","The UAE branch opened in Sharjah, bringing ANC's stocked curtain and upholstery fabrics closer to customers across the Emirates.",img.shop],
  ["Today","ANC serves customers through five branches in Lebanon, Syria, Oman, Iraq, and the UAE.",img.lab]
];

export default function AboutUs(){return <div className="au-page"><main>
  <section className="au-hero" style={{backgroundImage:`linear-gradient(#1a1c1c4d,#1a1c1c4d),url(${img.hero})`}}><div><span>ESTABLISHED 1998</span><h1>Legacy in Every Thread</h1><p>Luxury fabrics, dependable stock, and relationships built to last—<br/>serving homes and businesses with care since 1998.</p></div></section>
  <section className="au-section au-story"><div><h2>A Family Name Woven with Trust</h2><i/><p>Founded by Ahmad Al Najjar in Lebanon, ANC grew through a simple promise: offer beautiful, dependable fabrics and stand beside every customer. Today, our Sharjah branch supplies stocked ANC curtain, upholstery, and indoor fabrics for trade professionals and individual customers.</p><blockquote>“Fabrics That Make Every Space Feel Like Home—Crafted for Interiors of Distinction.”</blockquote><Link to="/catalogs">DISCOVER OUR FABRICS</Link></div><figure><img src={img.loom} alt="Fabric rolls and textile craft"/></figure></section>
  <section className="au-values-bg"><div className="au-section au-values"><article className="au-vision"><span>◉</span><h3>Our Vision</h3><p>To be the fabric partner customers remember for luxury quality, reliable stock, fair value, and a relationship that continues long after every order.</p></article><article className="au-mission"><b>♞</b><div><h3>Our Mission</h3><p>To help every customer find the right curtain or upholstery fabric through honest guidance, attentive service, and dependable delivery across the UAE.</p></div></article></div></section>
  <section className="au-section au-history"><header><h2>History in Motion</h2><p>Tracking our growth from a local workshop to an international icon.</p></header><div className="au-timeline">{timeline.map(([year,text,src],i)=><article className={i===1?"reverse":""} key={year}><div><h4>{year}</h4><p>{text}</p></div><i/><img className={i===0?"gray":""} src={src} alt={`${year} milestone`}/></article>)}</div></section>
  <section className="au-advantage"><div className="au-section au-adv-grid"><div className="au-adv-copy"><small>THE ANC ADVANTAGE</small><h2>Why Customers<br/>Choose ANC</h2>{[["◎","Luxury Fabric Quality","A carefully stocked range for curtains, upholstery, and indoor spaces."],["◉","Ready Stock","We sell stocked fabrics only, helping customers buy with confidence and receive orders quickly."],["♧","Service That Lasts","Competitive prices, attentive support, and long-term customer relationships are at the heart of ANC."]].map(([icon,title,text])=><div className="au-feature" key={title}><b>{icon}</b><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="au-adv-images"><img src={img.velvet} alt="Emerald velvet"/><img src={img.swatches} alt="Neutral fabric swatches"/></div></div></section>
  <section className="au-cta"><h2>Partner with Excellence</h2><p>Join our network of elite designers and bring your vision to life with ANC Najjar textiles.</p><div><Link to="/contact">CONTACT OUR AGENTS</Link><Link to="/catalogs">REQUEST CATALOG</Link></div></section>
  </main></div>}
