import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import "./AboutUs.css";

export const img = {
  hero:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2600&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  loom:"https://images.unsplash.com/photo-1640746942093-cec8e647596d?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  old:"https://lh3.googleusercontent.com/aida-public/AB6AXuAyCP4ueScOqupcrIVA7D8G_8NTKoChjNYbfxLog7G7CAemPB0cSc8SQK-3i8L8il8iyZ7wx3ycGDjA_o5sgY-T8ya0HBDn8A6_Shqa6wkgOSO0isRL2zq62AesyBzgZchpI8Ry8kHzgzbePmv2TAzKYPOI58o4VIuebj50pbUr2xZzUjjcvGOU8cb6ESj_0zj0M8Un4Frylien60U2U0GZ3Ehspy4lbLCeFgxftJ6GlV94Wjw9Q9scUak1DBAr9U6R6V7mTvnJteQ",
  shop:"https://media.istockphoto.com/id/1365312463/photo/modern-cafe-restaurant-interior-with-yellow-chair-against-window-with-city-view.jpg?s=2048x2048&w=is&k=20&c=tyFPYgSaYJ8koiPztLC1T3EucPPwTF5YXCOn-7GP_TA=",
  lab:"https://images.unsplash.com/photo-1624516268152-1e48624026ed?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  velvet:"https://lh3.googleusercontent.com/aida-public/AB6AXuBzkkL-lll8qThyUTPIDsyEoYav2pVb0-v_d2oG5PcRk08nZ9h1yiPKAxujMWtiVDvqcOupidNoV4rFhHMopqvdFj52hi86qcL0Eiox7Miut5BS-MOQ0_6bhEPdJ5lyRPKFRse1gXNahR9wRjdj7deeDQZGZ8XqppQsZgrxBSrtdTA9QpBgGi8rTOutH7RmzT62DQ3BCywDV9OZATn5YXp-KUHOBg73Ze-hLXjrqKNqgJkqbU9hnwerJ5t4kpvmh6WSKKYIKYxSLac",
  swatches:"https://plus.unsplash.com/premium_photo-1674747087104-516a4d6d316c?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  coroporate:"https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  residential:"https://images.unsplash.com/photo-1606744888344-493238951221?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  legacy:"https://images.unsplash.com/photo-1668956343245-c6330043be83?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  family:"https://images.unsplash.com/photo-1599696848652-f0ff23bc911f?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  customer:"https://media.istockphoto.com/id/1350603265/photo/i-love-those-pillows.jpg?s=2048x2048&w=is&k=20&c=twa6knbyVEneB-BYVCmNt7H46dwxHuIBAAm7M5DJn0o="
};
const links=[["HOME","/"],["CATALOGS","/catalogs"],["FABRIC MOCKUP","/mockup"],["ABOUT US","/about-us"],["SERVICES","/services"]];

export function LegacyAboutHeader(){const [open,setOpen]=useState(false);const {pathname}=useLocation();return <header className="au-header"><div className="au-nav"><Link className="au-brand" to="/">ANC NAJJAR</Link><nav className="au-links">{links.map(([n,to])=><Link className={pathname===to?"active":""} to={to} key={to}>{n}</Link>)}</nav><div className="au-actions"><button>EN/AR</button><Link to="/request-sample">REQUEST SAMPLE</Link></div><button className="au-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?"×":"☰"}</button></div>{open&&<nav className="au-mobile">{links.map(([n,to])=><Link onClick={()=>setOpen(false)} to={to} key={to}>{n}</Link>)}</nav>}</header>}
const timeline=[
  ["1998","Ahmad Al Najjar established the company in Lebanon with a commitment to quality fabrics and lasting customer relationships.",img.old],
  ["2022","The UAE branch opened in Sharjah, bringing ANC's stocked curtain and upholstery fabrics closer to customers across the Emirates.",img.shop],
  ["Today","ANC serves customers through five branches in Lebanon, Syria, Oman, Iraq, and the UAE.",img.lab]
];

export default function AboutUs(){return <div className="au-page"><main>
  <section className="au-hero" style={{backgroundImage:`linear-gradient(#1a1c1c4d,#1a1c1c4d),url(${img.legacy})`}}><div><span>ESTABLISHED 1998</span><h1>Legacy in Every Thread</h1><p>Luxury fabrics, dependable stock, and relationships built to last—<br/>serving homes and businesses with care since 1998.</p></div></section>
  <section className="au-section au-story"><div><h2>A Family Name Woven with Trust</h2><i/><p>Founded by Ahmad Al Najjar in Lebanon, ANC grew through a simple promise: offer beautiful, dependable fabrics and stand beside every customer. Today, our Sharjah branch supplies stocked ANC curtain, upholstery, and indoor fabrics for trade professionals and individual customers.</p><blockquote>“Fabrics That Make Every Space Feel Like Home—Crafted for Interiors of Distinction.”</blockquote><Link to="/catalogs">DISCOVER OUR FABRICS</Link></div><figure><img src={img.family} alt="Fabric rolls and textile craft"/></figure></section>
  <section className="au-values-bg"><div className="au-section au-values"><article className="au-vision" style={{backgroundImage:`linear-gradient(#0009,#0009),url(${img.customer})`,backgroundSize:"cover",backgroundPosition:"center"}}><span>◉</span><h3>Our Vision</h3><p>To be the fabric partner customers remember for luxury quality, reliable stock, fair value, and a relationship that continues long after every order.</p></article><article className="au-mission"><b>♞</b><div><h3>Our Mission</h3><p>To help every customer find the right curtain or upholstery fabric through honest guidance, attentive service, and dependable delivery across the UAE.</p></div></article></div></section>
  <section className="au-section au-history"><header><h2>History in Motion</h2><p>Tracking our growth from a local workshop to an international icon.</p></header><div className="au-timeline">{timeline.map(([year,text,src],i)=><article className={i===1?"reverse":""} key={year}><div><h4>{year}</h4><p>{text}</p></div><i/><img className={i===0?"gray":""} src={src} alt={`${year} milestone`}/></article>)}</div></section>
  <section className="au-advantage"><div className="au-section au-adv-grid"><div className="au-adv-copy"><small>THE ANC ADVANTAGE</small><h2>Why Customers<br/>Choose ANC</h2>{[["◎","Luxury Fabric Quality","A carefully stocked range for curtains, upholstery, and indoor spaces."],["◉","Ready Stock","We sell stocked fabrics only, helping customers buy with confidence and receive orders quickly."],["♧","Service That Lasts","Competitive prices, attentive support, and long-term customer relationships are at the heart of ANC."]].map(([icon,title,text])=><div className="au-feature" key={title}><b>{icon}</b><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="au-adv-images"><img src={img.velvet} alt="Emerald velvet"/><img src={img.swatches} alt="Neutral fabric swatches"/></div></div></section>
  <section className="au-cta"><h2>Partner with Excellence</h2><p>Join our network of elite designers and bring your vision to life with ANC Najjar textiles.</p><div><Link to="/contact">CONTACT OUR AGENTS</Link><Link to="/catalogs">REQUEST CATALOG</Link></div></section>
  </main></div>}
