import { useMemo, useState } from "react";
import { api, errorMessage } from "@/lib/api";
import { useApi } from "@/hooks/useApi";
import "./AdminProjectManagement.css";

type AdminProject={id:number;name:string;client:string;description?:string;status:"active"|"in_review"|"completed";is_favorite:boolean;archived_at?:string|null;fabrics_count:number;colors_count:number;notes_count:number;inspiration_count:number;members_count:number;timeline_count:number;owner?:{id:number;name:string;email:string}|null;created_at:string;updated_at:string};

export default function AdminProjectManagement(){
  const {data,loading,error,reload}=useApi(()=>api.getAll<AdminProject>("admin/projects",{per_page:100}),[]);
  const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [archive,setArchive]=useState("");const [selected,setSelected]=useState<AdminProject>();const [actionError,setActionError]=useState("");
  const projects=data?.data??[];const filtered=useMemo(()=>{const query=search.trim().toLowerCase();return projects.filter(project=>(!query||[project.name,project.client,project.owner?.name??"",project.owner?.email??""].some(value=>value.toLowerCase().includes(query)))&&(!status||project.status===status)&&(!archive||(archive==="archived"?!!project.archived_at:!project.archived_at)))},[projects,search,status,archive]);
  const remove=async(project:AdminProject)=>{if(!confirm(`Permanently delete “${project.name}” and all of its project data?`))return;setActionError("");try{await api.delete(`admin/projects/${project.id}`);if(selected?.id===project.id)setSelected(undefined);await reload()}catch(requestError){setActionError(errorMessage(requestError))}};
  return <main className="apm-main"><header className="apm-heading"><div><small>CRM & OPERATIONS</small><h1>Projects Management</h1><p>Browse customer project boards and permanently remove projects when required.</p></div><strong>{projects.length}<span>Total Projects</span></strong></header>
    <section className="apm-stats"><article><b>{projects.filter(p=>!p.archived_at).length}</b><span>Current</span></article><article><b>{projects.filter(p=>p.status==="in_review"&&!p.archived_at).length}</b><span>In Review</span></article><article><b>{projects.filter(p=>p.status==="completed"&&!p.archived_at).length}</b><span>Completed</span></article><article><b>{projects.filter(p=>p.archived_at).length}</b><span>Archived</span></article></section>
    <section className="apm-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search project, client, owner, or email…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="in_review">In Review</option><option value="completed">Completed</option></select><select value={archive} onChange={e=>setArchive(e.target.value)}><option value="">Current and archived</option><option value="current">Current only</option><option value="archived">Archived only</option></select><button onClick={()=>{setSearch("");setStatus("");setArchive("")}}>Clear</button></section>
    {(error||actionError)&&<p className="apm-message" role="alert">{error??actionError}</p>}{loading&&<p className="apm-message">Loading projects…</p>}
    <section className="apm-table"><header><span>Project</span><span>Owner</span><span>Status</span><span>Contents</span><span>Updated</span><span>Actions</span></header>{filtered.map(project=><article key={project.id}><div><b>{project.is_favorite&&"★ "}{project.name}</b><small>{project.client}</small></div><div><b>{project.owner?.name??"Unassigned"}</b><small>{project.owner?.email??"No owner account"}</small></div><span className={`apm-status ${project.archived_at?"archived":project.status}`}>{project.archived_at?"Archived":project.status.replace("_"," ")}</span><div className="apm-counts"><span>{project.fabrics_count} fabrics</span><span>{project.colors_count} colors</span><span>{project.members_count} members</span></div><time>{new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(project.updated_at))}</time><div className="apm-actions"><button onClick={()=>setSelected(project)}>View</button><button className="delete" onClick={()=>remove(project)}>Delete</button></div></article>)}{!loading&&!error&&filtered.length===0&&<p className="apm-message">No projects match the selected filters.</p>}</section>
    {selected&&<div className="apm-modal" role="dialog" aria-modal="true"><section><button className="apm-close" onClick={()=>setSelected(undefined)}>×</button><small>PROJECT #{selected.id}</small><h2>{selected.name}</h2><p>{selected.description||"No project description."}</p><dl><div><dt>Client</dt><dd>{selected.client}</dd></div><div><dt>Owner</dt><dd>{selected.owner?.name??"Unassigned"}<small>{selected.owner?.email}</small></dd></div><div><dt>Status</dt><dd>{selected.archived_at?"Archived":selected.status.replace("_"," ")}</dd></div><div><dt>Created</dt><dd>{new Intl.DateTimeFormat(undefined,{dateStyle:"long"}).format(new Date(selected.created_at))}</dd></div></dl><div className="apm-detail-counts">{[["Fabrics",selected.fabrics_count],["Colors",selected.colors_count],["Notes",selected.notes_count],["Images",selected.inspiration_count],["Members",selected.members_count],["Milestones",selected.timeline_count]].map(([label,count])=><span key={label}><b>{count}</b>{label}</span>)}</div><footer><button onClick={()=>setSelected(undefined)}>Close</button><button className="delete" onClick={()=>remove(selected)}>Permanently Delete</button></footer></section></div>}
  </main>
}
