import { type FormEvent, type ReactNode, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, errorMessage, type ApiResource, toFormData } from "@/lib/api";
import type { Catalog, Color } from "@/types/api";
import "./ProjectBoards.css";
import "./FabricPicker.css";

type Fabric = { name: string; collection?: string; code?: string; color?: string; image?: string };
type SavedColor = { name: string; hex: string };
type Member = { name: string; role?: string; initials?: string };
type Timeline = { title: string; date?: string; completed?: boolean };
type Project = { id:number; name:string; client:string; description?:string; cover_image?:string; status:"active"|"in_review"|"completed"; is_favorite:boolean; archived_at?:string|null; fabrics:Fabric[]; fabrics_count:number; saved_colors:SavedColor[]; notes:string[]; inspiration_images:string[]; members:Member[]; timeline:Timeline[]; recent_activity:{text:string;time?:string}[]; updated_human:string };

const blank = { name:"", client:"", description:"", status:"active" };

export function ProjectBoards() {
  const navigate = useNavigate();
  const [projects,setProjects]=useState<Project[]>([]);
  const [filter,setFilter]=useState("all");
  const [search,setSearch]=useState("");
  const [showCreate,setShowCreate]=useState(false);
  const [form,setForm]=useState(blank);
  const [cover,setCover]=useState<File|null>(null);
  const [error,setError]=useState("");
  const [saving,setSaving]=useState(false);
  const load=()=>api.getAll<Project>("projects",{per_page:100,include_archived:true}).then(r=>setProjects(r.data)).catch(e=>setError(errorMessage(e)));
  useEffect(()=>{load()},[]);
  const currentProjects=projects.filter(p=>!p.archived_at);
  const visible=projects.filter(p=>(filter==="archived"?!!p.archived_at:filter==="starred"?!p.archived_at&&p.is_favorite:!p.archived_at&&(filter==="all"||p.status===filter))&&(p.name+" "+p.client).toLowerCase().includes(search.toLowerCase()));
  const create=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");try{const body=toFormData(form,"cover_image_file",cover);const response=await api.postForm<ApiResource<Project>>("projects",body);navigate(`/projects/${response.data.id}`)}catch(e){setError(errorMessage(e))}finally{setSaving(false)}};
  const toggleFavorite=async(project:Project)=>{const r=await api.patch<ApiResource<Project>>(`projects/${project.id}/favorite`);setProjects(items=>items.map(item=>item.id===project.id?r.data:item))};
  return <main className="boards-page">
    <div className="boards-crumb">DASHBOARD　/　<b>PROJECT BOARDS</b></div>
    <header className="boards-head"><div><h1>Your Project Gallery</h1><p>Manage your textile specifications and moodboards for active client engagements.</p></div><button className="boards-new" onClick={()=>setShowCreate(true)}>＋　NEW PROJECT</button></header>
    <div className="boards-controls"><div className="boards-filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All Boards ({currentProjects.length})</button><button className={filter==="active"?"active":""} onClick={()=>setFilter("active")}>Active</button><button className={filter==="in_review"?"active":""} onClick={()=>setFilter("in_review")}>In Review</button><button className={filter==="completed"?"active":""} onClick={()=>setFilter("completed")}>Completed ({currentProjects.filter(p=>p.status==="completed").length})</button><button className={filter==="starred"?"active":""} onClick={()=>setFilter("starred")}>★ Starred ({currentProjects.filter(p=>p.is_favorite).length})</button><button className={filter==="archived"?"active":""} onClick={()=>setFilter("archived")}>Archived ({projects.length-currentProjects.length})</button></div><label>⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects…"/></label><i>Showing {visible.length} projects</i></div>
    {error&&<p className="boards-message" role="alert">{error}</p>}
    <section className="boards-grid">{visible.map(project=><article className="board-card" key={project.id}><div className="board-image">{project.cover_image?<img src={project.cover_image} alt=""/>:<div className="board-placeholder">ANC</div>}<span className={`board-status ${project.archived_at?"archived":project.status}`}>{project.archived_at?"archived":project.status.replace("_"," ")}</span><button className={`board-star ${project.is_favorite?"selected":""}`} aria-label={project.is_favorite?"Remove project from starred":"Add project to starred"} title={project.is_favorite?"Remove from Starred":"Add to Starred"} onClick={()=>toggleFavorite(project)}>{project.is_favorite?"★":"☆"}</button></div><Link to={`/projects/${project.id}`} className="board-copy"><h2>{project.name}</h2><p>Client: {project.client}</p><footer><span>▨ {project.fabrics_count} Fabrics Saved</span><span>◷ {project.updated_human}</span><b>•••</b></footer></Link></article>)}</section>
    {!error&&visible.length===0&&<p className="boards-message">No project boards match this view.</p>}
    <button className="board-starter" onClick={()=>setShowCreate(true)}><span>＋</span><strong>Start a New Design Board</strong><small>Upload your floor plans or moodboards to<br/>begin textile curation.</small></button>
    {showCreate&&<div className="board-modal" role="dialog" aria-modal="true"><form onSubmit={create}><button type="button" className="modal-close" onClick={()=>setShowCreate(false)}>×</button><p>NEW DESIGN BOARD</p><h2>Create a Project</h2><label>PROJECT NAME<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Hotel Lobby"/></label><label>CLIENT<input required value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Client or company"/></label><label>DESCRIPTION<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>STATUS<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="in_review">In Review</option><option value="completed">Completed</option></select></label><label>COVER IMAGE<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setCover(e.target.files?.[0]||null)}/></label><button className="boards-new" disabled={saving}>{saving?"CREATING…":"CREATE PROJECT"}</button></form></div>}
  </main>
}

export function ProjectBoardDetails(){
  const {projectId}=useParams();const navigate=useNavigate();const [project,setProject]=useState<Project>();const [error,setError]=useState("");const [showFabricPicker,setShowFabricPicker]=useState(false);const [showColorPicker,setShowColorPicker]=useState(false);const [showTimelineForm,setShowTimelineForm]=useState(false);const [showNoteForm,setShowNoteForm]=useState(false);
  const load=()=>api.get<ApiResource<Project>>(`projects/${projectId}`).then(r=>setProject(r.data)).catch(e=>setError(errorMessage(e)));
  useEffect(()=>{load()},[projectId]);
  if(error)return <main className="boards-page boards-message">{error}</main>;
  if(!project)return <main className="boards-page boards-message">Loading project board…</main>;
  const save=async(changes:Partial<Project>)=>{const next={...project,...changes};const payload={name:next.name,client:next.client,description:next.description||null,status:next.status,is_favorite:next.is_favorite,fabrics:next.fabrics,saved_colors:next.saved_colors,notes:next.notes,members:next.members,timeline:next.timeline,recent_activity:next.recent_activity};const r=await api.put<ApiResource<Project>>(`projects/${project.id}`,payload);setProject(r.data)};
  const ask=(message:string)=>window.prompt(message)?.trim();
  const addFabric=(catalog:Catalog,color:Color)=>{const displayName=`${catalog.name} — ${color.name||color.code}`;const savedColors=color.hex_code&&!project.saved_colors.some(saved=>saved.hex.toLowerCase()===color.hex_code?.toLowerCase())?[...project.saved_colors,{name:color.name||color.code,hex:color.hex_code}]:project.saved_colors;save({fabrics:[...project.fabrics,{name:displayName,collection:catalog.name,code:color.code,color:color.hex_code,image:color.swatch_path}],saved_colors:savedColors,recent_activity:[{text:`Added ${catalog.name} color ${color.code}`,time:"Just now"},...project.recent_activity]});setShowFabricPicker(false)};
  const upload=async(file?:File)=>{if(!file)return;const form=new FormData();form.append("image",file);const r=await api.postForm<ApiResource<Project>>(`projects/${project.id}/inspiration`,form);setProject(r.data)};
  return <main className="board-detail">
    <header className="detail-hero">{project.cover_image&&<img src={project.cover_image} alt=""/>}<div><Link to="/projects">← PROJECT BOARDS</Link><span>{project.archived_at?"archived":project.status.replace("_"," ")}</span><h1>{project.name}</h1><p>{project.client} · {project.description}</p></div></header>
    <div className="detail-actions"><label className="detail-status">PROJECT STATUS<select value={project.status} disabled={!!project.archived_at} onChange={event=>save({status:event.target.value as Project["status"],recent_activity:[{text:`Status changed to ${event.target.options[event.target.selectedIndex].text}`,time:"Just now"},...project.recent_activity]})}><option value="active">Active</option><option value="in_review">In Review</option><option value="completed">Completed</option></select></label><button onClick={()=>navigator.share?.({title:project.name,url:location.href})}>Share Project</button><button onClick={async()=>{const r=await api.post<ApiResource<Project>>(`projects/${project.id}/duplicate`,{});navigate(`/projects/${r.data.id}`)}}>Duplicate</button><button onClick={async()=>{await api.patch(`projects/${project.id}/archive`);navigate("/projects")}}>{project.archived_at?"Restore Project":"Archive Project"}</button><button className="danger" onClick={async()=>{if(confirm("Delete this project permanently?")){await api.delete(`projects/${project.id}`);navigate("/projects")}}}>Delete</button></div>
    <div className="detail-kanban"><div>
      <BoardSection title="Saved Fabric Collections" action="Add Fabric" onAction={()=>setShowFabricPicker(true)}>{project.fabrics.length?<div className="detail-fabrics">{project.fabrics.map((f,i)=><article key={i}>{f.image?<img src={f.image} alt=""/>:<div className="fabric-placeholder" style={{background:f.color||undefined}}>▨</div>}<small>{f.collection}</small><h3>{f.name}</h3><p>{f.code}</p><button className="remove-fabric" onClick={()=>save({fabrics:project.fabrics.filter((_,index)=>index!==i),recent_activity:[{text:`Removed ${f.name}`,time:"Just now"},...project.recent_activity]})}>Remove Collection</button></article>)}</div>:<Empty text="No fabrics saved yet."/>}</BoardSection>
      <BoardSection title="Saved Colors" action="Add Color" onAction={()=>setShowColorPicker(true)}>{project.saved_colors.length?<div className="detail-colors named">{project.saved_colors.map((color,i)=><article key={`${color.name}-${i}`}><span className="saved-color-swatch" style={{background:color.hex}} aria-hidden="true"/><div><b>{color.name}</b><small>{color.hex.toUpperCase()}</small></div><button className="remove-saved-color" title={`Delete ${color.name}`} aria-label={`Delete ${color.name}`} onClick={()=>save({saved_colors:project.saved_colors.filter((_,x)=>x!==i),recent_activity:[{text:`Deleted saved color ${color.name}`,time:"Just now"},...project.recent_activity]})}>Delete</button></article>)}</div>:<Empty text="No colors saved yet."/>}</BoardSection>
      <BoardSection title="Uploaded Inspiration Images"><label className="upload-tile">＋ Upload Image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><div className="detail-images">{project.inspiration_images.map((src,i)=><img src={src} key={i} alt="Project inspiration"/>)}</div></BoardSection>
    </div><aside>
      <BoardSection title="Notes" action="Add Note" onAction={()=>setShowNoteForm(true)}>{project.notes.length?<ul>{project.notes.map((n,i)=><li key={i}>{n}<button aria-label="Remove note" title="Remove note" onClick={()=>save({notes:project.notes.filter((_,x)=>x!==i)})}>×</button></li>)}</ul>:<Empty text="No notes yet."/>}</BoardSection>
      <BoardSection title="Project Members" action="Add Member" onAction={()=>{const name=ask("Member name");if(name)save({members:[...project.members,{name,role:ask("Role")||"Collaborator",initials:name.split(" ").map(x=>x[0]).join("").slice(0,2)}]})}}>{project.members.length?<ul>{project.members.map((m,i)=><li key={i}><b>{m.initials||m.name[0]}</b><span>{m.name}<small>{m.role}</small></span></li>)}</ul>:<Empty text="No members yet."/>}</BoardSection>
      <BoardSection title="Timeline" action="Add Milestone" onAction={()=>setShowTimelineForm(true)}>{project.timeline.length?<ul>{project.timeline.map((t,i)=><li key={i}><input type="checkbox" checked={!!t.completed} onChange={()=>save({timeline:project.timeline.map((x,n)=>n===i?{...x,completed:!x.completed}:x)})}/><span>{t.title}<small>{t.date}</small></span></li>)}</ul>:<Empty text="No milestones yet."/>}</BoardSection>
      <BoardSection title="Recent Activity">{project.recent_activity.length?<ul>{project.recent_activity.map((a,i)=><li key={i}>{a.text}<small>{a.time}</small></li>)}</ul>:<Empty text="No recent activity."/>}</BoardSection>
    </aside></div><button className="floating-fabric" onClick={()=>setShowFabricPicker(true)}>＋ Add Fabric</button>{showFabricPicker&&<FabricPicker onClose={()=>setShowFabricPicker(false)} onSelect={addFabric}/>} {showColorPicker&&<NamedColorPicker onClose={()=>setShowColorPicker(false)} onAdd={color=>{save({saved_colors:[...project.saved_colors,color],recent_activity:[{text:`Saved color ${color.name}`,time:"Just now"},...project.recent_activity]});setShowColorPicker(false)}}/>} {showTimelineForm&&<TimelineForm onClose={()=>setShowTimelineForm(false)} onAdd={milestone=>{save({timeline:[...project.timeline,milestone],recent_activity:[{text:`Added milestone ${milestone.title}`,time:"Just now"},...project.recent_activity]});setShowTimelineForm(false)}}/>} {showNoteForm&&<NoteForm onClose={()=>setShowNoteForm(false)} onAdd={note=>{save({notes:[...project.notes,note],recent_activity:[{text:"Added a project note",time:"Just now"},...project.recent_activity]});setShowNoteForm(false)}}/>}
  </main>
}

function BoardSection({title,action,onAction,children}:{title:string;action?:string;onAction?:()=>void;children:ReactNode}){return <section className="detail-panel"><header><h2>{title}</h2>{action&&<button onClick={onAction}>＋ {action}</button>}</header>{children}</section>}
function Empty({text}:{text:string}){return <p className="detail-empty">{text}</p>}

function FabricPicker({onClose,onSelect}:{onClose:()=>void;onSelect:(catalog:Catalog,color:Color)=>void}){
  const [catalogs,setCatalogs]=useState<Catalog[]>([]);const [catalog,setCatalog]=useState<Catalog>();const [colors,setColors]=useState<Color[]>([]);const [selectedColor,setSelectedColor]=useState<Color>();const [customName,setCustomName]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  useEffect(()=>{api.getAll<Catalog>("catalogs",{status:"published",per_page:100}).then(r=>setCatalogs(r.data)).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[]);
  const chooseCatalog=(selected:Catalog)=>{setCatalog(selected);setLoading(true);setError("");api.getAll<Color>("colors",{catalog_id:selected.id,per_page:100}).then(r=>setColors(r.data)).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))};
  const selectColor=(color:Color)=>{setSelectedColor(color);setCustomName(color.name||color.code)};
  return <div className="fabric-picker" role="dialog" aria-modal="true"><section><header><div><small>ADD FROM CATALOG</small><h2>{selectedColor?"Name Your Selected Color":catalog?`Choose a ${catalog.name} Color`:"Select a Fabric Collection"}</h2></div><button onClick={selectedColor?()=>setSelectedColor(undefined):catalog?()=>{setCatalog(undefined);setColors([])}:onClose}>{selectedColor||catalog?"← Back":"×"}</button></header>{error&&<p role="alert">{error}</p>}{loading&&<p>Loading available collections…</p>}{!loading&&!catalog&&<div className="catalog-picker-grid">{catalogs.map(item=><button key={item.id} onClick={()=>chooseCatalog(item)}>{item.thumbnail_path?<img src={item.thumbnail_path} alt=""/>:<span>ANC</span>}<b>{item.name}</b><small>{item.material||"Fabric Collection"}</small></button>)}</div>}{!loading&&catalog&&!selectedColor&&<div className="color-picker-grid">{colors.map(color=><button key={color.id} onClick={()=>selectColor(color)}><span style={{backgroundImage:color.swatch_path?`url(${color.swatch_path})`:undefined,backgroundColor:color.hex_code||"#777"}}/><b>{color.name||color.code}</b><small>{color.code} · {color.stock_status.replaceAll("_"," ")}</small></button>)}{colors.length===0&&<p>No active colors are available in this catalog.</p>}</div>}{catalog&&selectedColor&&<form className="selected-color-name" onSubmit={event=>{event.preventDefault();onSelect(catalog,{...selectedColor,name:customName.trim()})}}><span style={{backgroundImage:selectedColor.swatch_path?`url(${selectedColor.swatch_path})`:undefined,backgroundColor:selectedColor.hex_code||"#777"}}/><div><small>{catalog.name} · {selectedColor.code}</small><label>CUSTOM COLOR NAME<input required maxLength={100} value={customName} onChange={event=>setCustomName(event.target.value)} placeholder={selectedColor.name||selectedColor.code}/></label><p>You can keep the original catalog name or give this color a custom name for your project.</p><button className="boards-new">ADD TO PROJECT</button></div></form>}</section></div>
}

function NamedColorPicker({onClose,onAdd}:{onClose:()=>void;onAdd:(color:SavedColor)=>void}){
  const [name,setName]=useState("");const [hex,setHex]=useState("#8B6500");
  const submit=(event:FormEvent)=>{event.preventDefault();if(/^#[0-9a-f]{6}$/i.test(hex))onAdd({name:name.trim(),hex:hex.toUpperCase()})};
  return <div className="named-color-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><button className="modal-close" type="button" onClick={onClose}>×</button><small>SAVED COLORS</small><h2>Add a Named Color</h2><label>COLOR NAME<input required maxLength={100} value={name} onChange={event=>setName(event.target.value)} placeholder="Warm Sand"/></label><label>SELECT COLOR<div className="color-input-row"><input type="color" value={hex} onChange={event=>setHex(event.target.value.toUpperCase())}/><input required pattern="#[0-9A-Fa-f]{6}" value={hex} onChange={event=>setHex(event.target.value)} aria-label="Hex color"/></div></label><div className="color-preview" style={{background:hex}}><span>{name||"Color preview"}</span></div><button className="boards-new">ADD COLOR</button></form></div>
}

function TimelineForm({onClose,onAdd}:{onClose:()=>void;onAdd:(milestone:Timeline)=>void}){
  const [title,setTitle]=useState("");const [date,setDate]=useState("");const [completed,setCompleted]=useState(false);
  const submit=(event:FormEvent)=>{event.preventDefault();onAdd({title:title.trim(),date,completed})};
  return <div className="timeline-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><button className="modal-close" type="button" onClick={onClose}>×</button><small>PROJECT TIMELINE</small><h2>Add a Milestone</h2><p>Plan a key delivery, approval, installation, or project review.</p><label>MILESTONE TITLE<input required maxLength={255} value={title} onChange={event=>setTitle(event.target.value)} placeholder="Client fabric approval"/></label><label>DUE DATE<input required type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="timeline-completed"><input type="checkbox" checked={completed} onChange={event=>setCompleted(event.target.checked)}/><span>Mark this milestone as already completed</span></label><div className={`timeline-preview${completed?" complete":""}`}><b>{title||"Milestone title"}</b><span>{date?new Date(`${date}T00:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"long",year:"numeric"}):"Select a due date"}</span><small>{completed?"COMPLETED":"UPCOMING"}</small></div><footer><button type="button" onClick={onClose}>Cancel</button><button className="boards-new">ADD MILESTONE</button></footer></form></div>
}

function NoteForm({onClose,onAdd}:{onClose:()=>void;onAdd:(note:string)=>void}){
  const [note,setNote]=useState("");
  const submit=(event:FormEvent)=>{event.preventDefault();const value=note.trim();if(value)onAdd(value)};
  return <div className="note-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><button className="modal-close" type="button" onClick={onClose}>×</button><header><small>PROJECT JOURNAL</small><h2>Add a Project Note</h2><p>Capture decisions, client feedback, measurements, or installation details.</p></header><label>NOTE<textarea required autoFocus maxLength={2000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Write a clear note for your project team…"/><span>{note.length} / 2000 characters</span></label><div className="note-preview"><small>NOTE PREVIEW</small><p>{note||"Your project note will appear here."}</p></div><footer><button type="button" onClick={onClose}>Cancel</button><button className="boards-new" disabled={!note.trim()}>SAVE NOTE</button></footer></form></div>
}
